### ISSUE TITLE
Qtile TODO

### ISSUE THREAD

**Issue by glazrtom** [glazrtom/dotfiles#25]
- [ ] repair my setup script shortcut
- [ ] bind keys for audio
- [ ] clipboard neovim doesn't work
- [x] add choices for shutdown/sleep etc.
